In [3]:
import pandas as pd
import numpy as np

In [7]:
t_ex = pd.read_csv('ex1data1.txt', header = None)

In [99]:
fval = np.array(t_ex[0])
X = np.column_stack((np.ones((97)),fval))
y = np.array(t_ex[1])

In [100]:
initTheta = np.zeros((2))

In [115]:
alpha = 0.01
iterations = 1500

In [128]:
def computeCost(cX, cy, ct):
    m = len(cy)
    predictions = cX @ ct
    sqrErrors = (predictions - cy) ** 2
    J = 1 / (2 * m) * sum(sqrErrors)
    return J
testTheta = np.array([-1, 2])
testJ = computeCost(X, y, testTheta)
testJ

54.24245508201238

In [126]:
def gradientDescent(gX, gy, gt, alpha, iterations):
    for i in range(iterations):
        m = len(gy)
        delta = ((gX @ gt - gy) @ gX) / m
        gt = gt - (alpha * delta)
    return gt

In [127]:
theta = gradientDescent(X, y, initTheta, alpha, iterations)
print(theta)

[-3.63029144  1.16636235]


In [134]:
a = np.array([1, 2])
b = np.array([[2, 4], [3, 5]])
c = a @ b
print(c)
print(np.shape(a))
print(np.shape(b))
print(np.shape(c))

[ 8 14]
(2,)
(2, 2)
(2,)


In [152]:
w = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1 , 2])
z = np.column_stack((v,w))
print(z)
z2 = np.sum(z, 0) #0 for column sum, 1 for row sum
print(z2)

[[1 1 2 3]
 [2 4 5 6]]
[3 5 7 9]


In [153]:
column_v = np.array([1, 2])
#w[:,0] = column_v * w[:,0]
#w[:,1] = column_v * w[:,1]
(w.T * column_v).T

array([[ 1,  2,  3],
       [ 8, 10, 12]])